apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/pi-cluster/infrastructure/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
