apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: homepage-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: homepage-config
  values:
    image:
      tag: "latest"
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: false # we’re doing ingress separately
    persistence:
      enabled: false # not storing on disk (or swap to true + storageClass)
